version: "3"
services:
  app1:
    image: astandre/app1
    build:
      context: ./apps/app1
      dockerfile: Dockerfile
    container_name: "app1"
    ports:
      - "3000:3000"
    labels:
      kompose.service.type: NodePort


  #  app2:
  #    build: ./apps/app2
  #    ports:
  #      - "3001:3001"
  mongodb:
    image: "mongo"
    container_name: "mongodb"
    volumes:
      - /mongo-volume:/data/db
    ports:
      - "27017:27017"
